// export { default as adygeya } from './getAdygeaMNO.js';
// export { default as bashk } from './getBashkMNO.js';
// export { default as buryat } from './getBuryatMNO.js';
// export { default as dag } from './getDagMNO.js';
// export { default as ingush } from './getIngushMNO.js';
// export { default as karelia } from './getKareliaMNO.js';
// export { default as kbr } from './getKBRMNO.js';
// export { default as kchr } from './getKchrMNO.js';
// export { default as komi } from './getKomiMNO.js';
// export { default as khakas } from './getKhakasMNO.js';
// export { default as kras } from './getKrasMNO.js';
// export { default as mosk } from './getMoskMNO.js';
// export { default as minProf } from './getNewsMinProf.js';
// export { default as mnwo } from './getNewsMNWO.js';
// export { default as mari } from './getMariMNO.js';
// export { default as mordov } from './getMordovMNO.js';
// export { default as sakha } from './getSakhaMNO.js';
// export { default as alania } from './getAlaniaMNO.js';
// export { default as tatar } from './getTatarMNO.js';
export { default as tuva } from './getTuvaMNO.js';
export { default as udmur } from './getUdmurMNO.js';