// export { default as adygeya } from './getAdygeaMNO.js';
// export { default as bashk } from './getBashkMNO.js';
// export { default as buryat } from './getBuryatMNO.js';
// export { default as dag } from './getDagMNO.js';
// export { default as ingush } from './getIngushMNO.js';
// export { default as karelia } from './getKareliaMNO.js';
// export { default as kbr } from './getKBRMNO.js';
// export { default as kchr } from './getKchrMNO.js';
// export { default as komi } from './getKomiMNO.js';
// export { default as khakas } from './getKhakasMNO.js';
// export { default as kras } from './getKrasMNO.js';
// export { default as mosk } from './getMoskMNO.js';
// export { default as minProf } from './getNewsMinProf.js';
// export { default as mnwo } from './getNewsMNWO.js';
// export { default as mari } from './getMariMNO.js';
// export { default as mordov } from './getMordovMNO.js';
// export { default as sakha } from './getSakhaMNO.js';
// export { default as alania } from './getAlaniaMNO.js';
// export { default as tatar } from './getTatarMNO.js';
// export { default as tuva } from './getTuvaMNO.js';
// export { default as udmur } from './getUdmurMNO.js';
// export { default as chech } from './getChechMNO.js';
// export { default as chuvash } from './getChuvashMNO.js';
// export { default as altkray } from './getAltKrayMNO.js';
// export { default as zbaykray } from './getZbayKray.js';
// export { default as kamkray } from './getKamKrayMNO.js';
// export { default as krasnodarkray } from './getKrasnodarKrayMNO.js';
// export { default as permkray } from './getPermKrayMNO.js';
// export { default as primorsk } from './getPrimorskMNO.js';
// export { default as khabarkray } from './getHabarKrayMNO.js';
// export { default as amurobl } from './getAmurOblMNO.js';
// export { default as arkhobl } from './getArkhOblMNO.js';
// export { default as astrobl } from './getAstrObl.js';
// export { default as bryaobl } from './getBryaOblMNO.js';
// export { default as vladimobl } from './getVladimOblMNO.js';
// export { default as vologodobl } from './getVologodOblMNO.js';
// export { default as voronezhobl } from './getVoronezhOblMNO.js';
// export { default as irkobl } from './getIrkOblMNO.js';
// export { default as kalinobl } from './getKalinOblMNO.js';
// export { default as kalugobl } from './getKalugOblMNO.js';
// export { default as kemobl } from './getKemOblMNO.js';
// export { default as kirovobl } from './getKirovOblMNO.js';
// export { default as kostromobl } from './getKostromOblMNO.js';
// export { default as kurgobl } from './getKurgOblMNO.js';
// export { default as kurskobl } from './getKurskOblMNO.js';
// export { default as lenobl } from './getLenOblMNO.js';
// export { default as lipobl } from './getLipOblMNO.js';
// export { default as magadobl } from './getMagadOblMNO.js';
// export { default as murmanobl } from './getMurmanOblMNO.js';
// export { default as nnovobl } from './getNNovOblMNO.js';
// export { default as novgorobl } from './getNovgorOblMNO.js';
// export { default as novosibobl } from './getNovosibOblMNO.js';
// export { default as omskobl } from './getOmskOblMNO.js';
// export { default as penzobl } from './getPenzOblMNO.js';
// export { default as pskovobl } from './getPskovOblMNO.js';
// export { default as rostovobl } from './getRostovOblMNO.js';
// export { default as ryazanobl } from './getRyazanOblMNO.js';
// export { default as samarobl } from './getSamarOblMNO.js';
// export { default as saratobl } from './getSaratOblMNO.js';
export { default as sakhalobl } from './getSakhalinOblMNO.js';
export { default as sverdobl } from './getSverdOblMNO.js';
export { default as smolobl } from './getSmolOblMNO.js';
export { default as tambobl } from './getTambOblMNO.js';
export { default as tverobl } from './getTverOblMNO.js';
export { default as tomskobl } from './getTomskOblMNO.js';
export { default as tulaobl } from './getTulaOblMNO.js';
export { default as tyumenobl } from './getTyumenOblMNO.js';
export { default as ulyanobl } from './getUlyanOblMNO.js';
export { default as chelyabobl } from './getChelyabOblMNO.js';
export { default as yarobl } from './getYarOblMNO.js';
export { default as gormosk } from './getGorMoskMNO.js';
export { default as gorspb } from './getGorSPBMNO.js';
export { default as evr_aob } from './getEvrAObMNO.js';
export { default as hm_aok } from './getHMAOkMNO.js';
export { default as chuck_aok } from './getChuckAOkMNO.js';
export { default as yamnen_aok } from './getYamNenOkMNO.js';